@PaymentsClient.WebApi_HostAddress = https://localhost:7277

### PingController-Ping
GET {{PaymentsClient.WebApi_HostAddress}}/api/ping/
Accept: application/json

### AuthenticationController-InitializeAsync
POST {{PaymentsClient.WebApi_HostAddress}}/api/authentication/initialize
Content-Type: application/json

{
  "userHash": "test-user-id",
  "redirectUrl": "http://localhost:5178/login-redirect"
}

### AuthenticationController-CompleteAsync
POST {{PaymentsClient.WebApi_HostAddress}}/api/authentication/complete
Content-Type: application/json

{
  "code": ""
}

### AccountsController-GetAccountsAsync
POST {{PaymentsClient.WebApi_HostAddress}}/api/accounts
Content-Type: application/json

{
  "accessToken": "ygAAAAVDaXBoZXJ0ZXh0AJAAAAAAOVFESOOfRc_HOr3rlJCYXnBsPGm3ts1qxxs3KwN8pNX8P76URHPc234mqWOJJMpmP-to5MT705GLTpc16K13FX9_7T4l7VIyyJkF4oyUGL1obYcWfJa8nbHwIz7txYB30ENOJvHLnUsuEV5Eh1AV6gKVs7w6v1plgKSLQ7x0Eo8KfNKVJpVbRZ2sFO1fALFQBUl2ABAAAAAALflLFQ_lhhkrHfoCc4pnNxBLZXlJZAAAAAAAAA"
}

### AccountsController-GetTransactionsAsync
POST {{PaymentsClient.WebApi_HostAddress}}/api/accounts/transactions
Content-Type: application/json

{
  "accessToken": "",
  "accountId": "",
  "fromDate": "2024-06-01",
  "withDetails": true
}

### PaymentsController-CreatePaymentAsync
POST {{PaymentsClient.WebApi_HostAddress}}/api/payments/create
Content-Type: application/json

{
  "userHash": "test-user-id",
  "request": {
    "destination": {
      "bban": {
        "bankCode": "0001",
        "accountNumber": ""
      },
      "name": "Checking Account"
    },
    "amount": {
      "value": "25.50",
      "currency": "DKK"
    }
  },
  "redirectUrl": "http://localhost:5178/payment-redirect",
  "issuePayerToken": true
}

### PaymentsController-RefreshStatusAsync
POST {{PaymentsClient.WebApi_HostAddress}}/api/payments/status
Content-Type: application/json

{
  "paymentId": ""
}